SELECT TITLE, NAME
FROM MOVIE JOIN MOVIEEXEC
ON MOVIE.PRODUCERC#=MOVIEEXEC.CERT# AND NAME = (SELECT NAME FROM MOVIEEXEC, MOVIE
WHERE MOVIEEXEC.CERT#=MOVIE.PRODUCERC# AND TITLE = 'Star Wars');

SELECT DISTINCT NAME
FROM MOVIEEXEC JOIN MOVIE
 ON CERT# = MOVIE.PRODUCERC# 
JOIN STARSIN
 ON MOVIE.TITLE = STARSIN.MOVIETITLE AND STARNAME = 'Harrison Ford';

SELECT DISTINCT NAME, STARNAME
FROM MOVIE INNER JOIN STUDIO
 ON NAME = STUDIONAME
INNER JOIN STARSIN
 ON MOVIETITLE = TITLE
ORDER BY NAME;

SELECT STARNAME
FROM MOVIE, STARSIN
WHERE PRODUCERC# = (SELECT CERT# FROM MOVIEEXEC WHERE NETWORTH >= ALL (SELECT NETWORTH FROM MOVIEEXEC))
AND MOVIETITLE = TITLE;


SELECT STARNAME, TITLE
FROM MOVIE JOIN STARSIN
ON PRODUCERC# = (SELECT CERT# FROM MOVIEEXEC WHERE NETWORTH >= ALL (SELECT NETWORTH FROM MOVIEEXEC))
AND MOVIETITLE = TITLE;

SELECT NAME, MOVIETITLE
FROM STARSIN RIGHT JOIN MOVIESTAR
ON NAME = STARNAME
WHERE MOVIETITLE IS NULL;


