/*
INSERT INTO MOVIESTAR(NAME, BIRTHDATE)
VALUES ('Nicole Kidman', 20/06/1967);
*/

/*
DELETE FROM MOVIEEXEC
WHERE NETWORTH < 30000000;
*/

/*
DELETE FROM MOVIESTAR
WHERE ADDRESS IS NULL;
*/