SELECT NAME
FROM MOVIESTAR
WHERE GENDER='F' AND NAME IN (SELECT NAME FROM MOVIEEXEC WHERE NETWORTH > 10000000);

SELECT NAME
FROM MOVIESTAR
WHERE NAME NOT IN (SELECT NAME FROM MOVIEEXEC);

SELECT TITLE
FROM MOVIE
WHERE LENGTH > (SELECT LENGTH FROM MOVIE WHERE TITLE='Star Wars');

SELECT  MOVIE.TITLE, MOVIEEXEC.NAME
FROM MOVIEEXEC, MOVIE
WHERE MOVIE.PRODUCERC#=MOVIEEXEC.CERT# AND NETWORTH > (SELECT NETWORTH FROM MOVIEEXEC WHERE NAME = 'Merv Griffin');