SELECT NAME
FROM MOVIESTAR
WHERE GENDER='M'
INTERSECT
SELECT STARNAME
FROM STARSIN
WHERE MOVIETITLE='The Usual Suspects';

SELECT DISTINCT STARNAME
FROM STARSIN, MOVIE
WHERE (MOVIEYEAR='1995' AND STUDIONAME='MGM');

SELECT DISTINCT MOVIEEXEC.NAME
FROM MOVIEEXEC, MOVIE
WHERE STUDIONAME='MGM' AND PRODUCERC#=CERT#;

SELECT TITLE
FROM MOVIE
WHERE LENGTH > (SELECT LENGTH FROM MOVIE WHERE TITLE='Star Wars');

SELECT NAME
FROM MOVIEEXEC
WHERE NETWORTH > (SELECT NETWORTH FROM MOVIEEXEC WHERE NAME='Stephen Spielberg');


SELECT TITLE
FROM MOVIE, MOVIEEXEC
WHERE NETWORTH > (SELECT NETWORTH FROM MOVIEEXEC WHERE NAME='Stephen Spielberg') AND PRODUCERC#=CERT#;