SELECT TITLE, YEAR, LENGTH
FROM MOVIE
WHERE YEAR < 2000 AND (LENGTH > 120 OR LENGTH IS NULL);

SELECT NAME, GENDER
FROM MOVIESTAR
WHERE NAME like 'J%' AND BIRTHDATE > 1948
ORDER BY NAME DESC;

SELECT STUDIONAME, COUNT(STARNAME)
FROM MOVIE JOIN STARSIN ON TITLE = MOVIETITLE
GROUP BY STUDIONAME;

SELECT NAME, COUNT(MOVIETITLE) AS num_films
FROM MOVIESTAR, STARSIN
WHERE NAME = STARNAME
GROUP BY NAME;

SELECT NAME, TITLE, YEAR
FROM STUDIO JOIN MOVIE ON STUDIONAME = NAME
WHERE YEAR >= ALL (SELECT YEAR FROM MOVIE WHERE STUDIONAME = NAME);

SELECT NAME
FROM MOVIESTAR
WHERE GENDER='M' AND BIRTHDATE >= ALL (SELECT BIRTHDATE FROM MOVIESTAR WHERE GENDER = 'M');

SELECT STARNAME, STUDIONAME, COUNT(MOVIETITLE)
FROM MOVIE AS M JOIN STARSIN ON TITLE = MOVIETITLE
GROUP BY STARNAME, M.STUDIONAME
HAVING COUNT(MOVIETITLE) >= ALL 
(SELECT COUNT(MOVIETITLE) FROM MOVIE JOIN STARSIN ON TITLE = MOVIETITLE
 WHERE STUDIONAME = M.STUDIONAME GROUP BY STARNAME, STUDIONAME);

SELECT TITLE, YEAR, COUNT(STARNAME)
FROM MOVIE JOIN STARSIN ON TITLE = MOVIETITLE
GROUP BY TITLE, YEAR
HAVING COUNT(STARNAME) > 2;