SELECT MODEL, SPEED as MHz, RAM as GB
FROM PC
WHERE PRICE < 1200;

SELECT DISTINCT MAKER
FROM PRODUCT
WHERE TYPE='Printer';

SELECT MODEL, RAM, SCREEN
FROM laptop
WHERE PRICE > 1000;

SELECT *
FROM printer
WHERE color='y';

SELECT MODEL, SPEED, HD
FROM PC
WHERE (CD='12x' OR CD='16x') AND PRICE < 2000;