/*
INSERT INTO CLASSES
VALUES ('Nelson', 'bb', 'Britain', 9, 16, 34000);

INSERT INTO SHIPS
VALUES ('Nelson', 'Nelson', 1927);

INSERT INTO CLASSES
VALUES ('Nelson', 'bb', 'Britain', 9, 16, 34000);

INSERT INTO SHIPS
VALUES ('Rodney', 'Nelson', 1927);
*/

/*
DELETE FROM SHIPS
WHERE NAME IN (SELECT SHIP FROM OUTCOMES WHERE RESULT = 'sunk');
*/

/*
UPDATE CLASSES
SET BORE = BORE*2.5, DISPLACEMENT = DISPLACEMENT/1.1;
*/