SELECT count(CLASS) as NO_CLASS
FROM CLASSES
WHERE TYPE = 'bb';

SELECT CLASS, AVG(NUMGUNS)
FROM CLASSES
WHERE TYPE = 'bb'
GROUP BY CLASS;

SELECT AVG(NUMGUNS) AS AvgNumGuns
FROM CLASSES
WHERE TYPE = 'bb';

SELECT CLASSES.CLASS, MIN(LAUNCHED) AS FirstYear, MAX(LAUNCHED) AS LastYear
FROM CLASSES JOIN SHIPS ON CLASSES.CLASS = SHIPS.CLASS
GROUP BY CLASSES.CLASS;

SELECT SHIPS.CLASS, COUNT(SHIP)
FROM SHIPS JOIN OUTCOMES ON NAME = SHIP
WHERE RESULT = 'sunk'
GROUP BY CLASS;

SELECT CLASS, COUNT(SHIP) as [Num of sunk ships]
FROM SHIPS JOIN OUTCOMES O ON NAME = SHIP WHERE RESULT = 'sunk' AND CLASS IN
 (SELECT C.CLASS FROM CLASSES C JOIN SHIPS ON C.CLASS = SHIPS.CLASS 
		GROUP BY C.CLASS HAVING COUNT(SHIPS.NAME) > 2)
GROUP BY CLASS;

SELECT COUNTRY, AVG(BORE) AS AvgBore
FROM CLASSES
GROUP BY COUNTRY;
