SELECT DISTINCT NAME
FROM SHIPS JOIN OUTCOMES ON NAME = SHIP
WHERE BATTLE IS NOT NULL AND (NAME LIKE 'C%' OR NAME LIKE 'K%');

SELECT NAME, COUNTRY
FROM SHIPS JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS
WHERE NAME NOT IN (SELECT SHIP FROM OUTCOMES WHERE RESULT = 'sunk');

SELECT COUNTRY, COUNT(RESULT)
FROM CLASSES LEFT JOIN SHIPS ON CLASSES.CLASS = SHIPS.CLASS
LEFT JOIN OUTCOMES ON NAME = SHIP
WHERE RESULT = 'sunk' OR RESULT IS NULL
GROUP BY COUNTRY;

SELECT BATTLE
FROM OUTCOMES
GROUP BY BATTLE
HAVING COUNT(SHIP) > (SELECT COUNT(SHIP) FROM OUTCOMES WHERE BATTLE = 'Guadalcanal' GROUP BY BATTLE);

SELECT BATTLE
FROM OUTCOMES
GROUP BY BATTLE
HAVING COUNT(SHIP) > (SELECT COUNT(SHIP) FROM OUTCOMES WHERE BATTLE = 'Surigao Strait' GROUP BY BATTLE);

SELECT NAME, DISPLACEMENT, NUMGUNS
FROM SHIPS JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS
WHERE DISPLACEMENT <= ALL (SELECT DISPLACEMENT FROM CLASSES) AND 
NUMGUNS >= ALL (SELECT NUMGUNS FROM CLASSES WHERE DISPLACEMENT <= ALL (SELECT DISPLACEMENT FROM CLASSES));

SELECT COUNT(*) AS num_ships
FROM OUTCOMES JOIN BATTLES AS B ON BATTLE = NAME
WHERE RESULT = 'damaged' AND SHIP IN 
(SELECT SHIP FROM OUTCOMES JOIN BATTLES ON BATTLE = NAME
WHERE RESULT = 'ok' AND DATE > B.DATE);

SELECT O1.SHIP
FROM OUTCOMES AS O1 JOIN BATTLES AS B ON BATTLE=B.NAME
WHERE RESULT = 'damaged' AND SHIP IN 
(SELECT O2.SHIP FROM OUTCOMES AS O2 JOIN BATTLES AS A ON O2.BATTLE = A.NAME
WHERE O2.RESULT = 'ok' AND A.DATE > B.DATE AND
(SELECT COUNT(OO1.SHIP) FROM OUTCOMES AS OO1 WHERE OO1.BATTLE=B.NAME) <
	(SELECT COUNT(OO2.SHIP) FROM OUTCOMES AS OO2 WHERE OO2.BATTLE=A.NAME));